#!/usr/bin/env python

import os
import sys
import subprocess

args = ' '.join(sys.argv[1:])
args = args.replace('\"', '\\\"')
manof_path = os.path.join(os.path.dirname(os.path.realpath(__file__)))
subprocess.run(f'source {manof_path}/venv/bin/activate && python {manof_path}/manof.py {args}',
               check=True,
               shell=True,
               executable='/bin/bash')
